name: Official SonarQube Scan
# Warning: changing name would change URL in the marketplace
description: >
  Scan your code with SonarQube Server and Cloud to detect issues in 30+ languages. (Formerly SonarQube and SonarCloud)

branding:
  icon: check
  color: green
inputs:
  args:
    description: Additional arguments to the Sonar Scanner CLI
    required: false
    default: ""
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: "."
  scannerVersion:
    description: Version of the Sonar Scanner CLI to use
    required: false
    # to be kept in sync with sonar-scanner-version
    default: 7.2.0.5079
  scannerBinariesUrl:
    description: URL to download the Sonar Scanner CLI binaries from
    required: false
    default: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli
runs:
  using: node20
  main: dist/index.js
