name: Update Tags

on:
  push:
    tags:
      - v*.*.*

jobs:
  generate:
    runs-on: github-ubuntu-latest-s
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Parse semver
        uses: madhead/semver-utils@4cf918affe9106ea59f86c6250e5ec4570ac4389 # v5.0.0
        id: version
        with:
          version: ${{ github.ref_name }}

      - name: Update tags
        run: |
          TAGS='v${{ steps.version.outputs.major }} v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}'

          for t in $TAGS; do
            git tag -f "$t"
            git push origin ":$t" 2>/dev/null || true
            git push origin "$t"
          done
